### ISSUE TITLE
Revisar configuração do CI

### ISSUE THREAD

**Issue by reebr** [resumemakers/resume-maker-web#10]
O CI não está executando quando ocorre commits e pull requests nesse repositório, acho que ele foi configurado para esse repo:
- https://github.com/williangl/resume-maker-web

E não esse:
- https://github.com/resumemakers/resume-maker-web

Pelo link do badge no README:
```
https://travis-ci.org/williangl/resume-maker-web.svg?branch=master
```

**Comment by williangl** [comment]
Dei uma olhada nas paradas aqui e aparentemente o travis não deixa eu habilitar ele para a organização, apenas no meu fork.

**Comment by reebr** [comment]
@dunossauro acho que esse tipo de coisa tem que ser configurada pelo owner da organização.

**Comment by dunossauro** [comment]
Corrigido <3
