### ISSUE TITLE
Definir parâmetros necessários para serem processados pelo backend

### ISSUE THREAD

**Issue by reebr** [resumemakers/resume-maker-web#3]
Eu inicializei o desenvolvimento do front-end em um fork, porém não ficou explicito quais são os parâmetros requeridos pelo back-end. Tem o [curriculum-online][1] e o [resume-maker][2] mas sem esse tipo de informação clara.

Analisando a feature [resume][3], seria basicamente esses parâmetros:
```json
{
        "name": "George the Martian",
        "function": "Youtube senior analyst",
        "phone": "+55 287298121",
        "email": "George@martian.com",
        "address": "73 N. Oak Drive - Dyersburg, TN 38024",
        "education": [
            ["PhD in the streets - Harvard",
             "2001"],

            ["PhD in python - PyCon",
             "every year"]

        ],
        "experience": [
            ["Scroll Master",
             "Mai 2003 - Jun 2007",
             "Scroll the scroll of the mouse pretending to program"],

            ["Garbage collector",
             "Jan 2000 - Mai 2003",
             "Collecting garbage in other codes"]

        ],
        "skills": [
            ["Python", 5],
            ["Java", 2],
            ["C++", 4],
            ["JS", 1]
            ],

        "languages": [
            ["Elvish", "Fluent"],
            ["English", "Basic"]
            ]
    }
```
Inicialmente pode ser desenvolvido enviando isso mesmo?

[1]:https://github.com/dunossauro/curriculum-online
[2]:https://github.com/dunossauro/resume-maker
[3]:https://github.com/dunossauro/resume-maker/blob/master/tests/resume.feature

**Comment by dunossauro** [comment]
Eu estava pensando em deixar

```python
KEYS = [
    "name",
    "function",
    "phone",
    "email",
    "address",
    "portfolio",
    "education",
    "experience",
    "skills",
    "languages",
]
```

Onde
```
education
experience
skills
languages
```

Seriam listas de parâmetros. o que vc acha? Eu tava escrendo o checker com esses params.

**Comment by dunossauro** [comment]
Se liga aqui: https://github.com/dunossauro/resume-maker-web/blob/master/resumemaker/modules/json_checker.py
