### ISSUE TITLE
Criar travis-ci

### ISSUE THREAD

**Issue by dunossauro** [resumemakers/resume-maker-web#4]
@williangl, dá pra resolver essa parada? xD

**Comment by dunossauro** [comment]
@reebr se bem que a gente poderia usar o ci do gilab. O que vc acha?

**Comment by reebr** [comment]
@dunossauro vai mover o projeto pra lá?

Dá pra fazer essa integração com os apps aqui no GitHub, só que pra fazer o que o Gitlab já tem "nativo" a gente vai precisar usar uns três serviços diferentes. 😄

**Comment by williangl** [comment]
Faço sim. Mas agora estou na dúvida, preferem manter no github ou migrar pro gitlab? @reebr @dunossauro

**Comment by williangl** [comment]
outra pergunta, faremos a parada de criar branch para cada issue ou commitamos direto na dev?
